name: Build Android Project

on: [push, pull_request]

jobs:
  buildAndroid:
    name: Build Questcraft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # - uses: actions/cache@v3
      #   with:
      #     path: Library
      #     key: Library-Android
      #     restore-keys: Library-

      # - uses: jlumbroso/free-disk-space@v1.3.1

      # - name: unset
      #   run:
      #     unset JAVA_TOOL_OPTIONS
      
      # - uses: game-ci/unity-builder@v4.2.3
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #     UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #     UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #   with:
      #     allowDirtyBuild: true
      #     unityVersion: 2021.3.37f1
      #     targetPlatform: Android
      #     androidTargetSdkVersion: '32'

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: Build
      #     path: build

      # - name: Prepare APK for Release
      #   run: |
      #     APK_NAME="Questcraft-$(date +%Y-%m-%d)"
      #     sudo mv build/Android/*.apk build/Android/${APK_NAME}.apk
      #     echo "APK_NAME=${APK_NAME}.apk" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "release-$(date +%Y%m%d%H%M%S)"
          release_name: "Questcraft-$(date +%Y-%m-%d)"
          body: |
            Release for Questcraft-$(date +%Y-%m-%d)
      
            there is no guarantee these builds will work.
            Do not get support for these builds from the questcraft discord.

      # - name: Upload Release Asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: build/Android/${{ env.APK_NAME }}.apk
      #     asset_name: ${{ env.APK_NAME }}.apk
      #     asset_content_type: application/vnd.android.package-archive
